improving readme and including biotope.sh link #87
biotope/biotope-cli pull request #103
Opened 2020-01-24 14:07 UTC by IvailoStoyanov

2020-01-24 14:09 UTC, IvailoStoyanov commented
solving: https://github.com/biotope/biotope/issues/87

2020-01-29 08:07 UTC, rhafner requested changes

2020-01-29 08:07 UTC, rhafner commented on Readme.md
> +Biotope helps you to build, distribute and adopt a library of web components with a consistent design and of high quality across all your websites and apps. With Biotope you can easily collaborate wi
```suggestion

Biotope helps you to build, distribute and adopt a library of web components with a consistent design and of high quality across all your websites and apps. With Biotope you can easily collaborate with your team to develop and maintain the user interface of all your digital experiences from a single location.
```
Could you add a line break here to start the text on a new line after the badges?

2020-01-29 10:11 UTC, rhafner approved these changes

2020-02-19 07:04 UTC, timomayer approved these changes

2020-02-19 07:05 UTC, merged